# Generated by Django 4.2 on 2026-03-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelProfile',
            new_name='ModelAccount',
        ),
    ]
