# Generated by Django 4.2 on 2026-03-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_modelprofile_modelaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelAccount',
        ),
    ]
