# Generated by Django 4.1.13 on 2026-01-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Please select a subject', 'Please select a subject'), ('Apply to become a model', 'Apply to become a model'), ('Agency / Brand Collaboration Inquiry', 'Agency / Brand Collaboration Inquiry'), ('General Questions / Support', 'General Questions / Support'), ('Technical Issues', 'Technical Issues'), ('Media / Press Inquiry', 'Media / Press Inquiry'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
