# Generated by Django 4.1.13 on 2026-01-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact_alter_signup_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('feedback', models.CharField(choices=[('Suggestion', 'Suggestion'), ('Bug Report', 'Bug Report'), ('Complaint', 'Complaint'), ('Appreciation', 'Appreciation'), ('Other', 'Other')], max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Technical Issues', 'Technical Issues'), ('Apply to become a model', 'Apply to become a model'), ('Agency / Brand Collaboration Inquiry', 'Agency / Brand Collaboration Inquiry'), ('General Questions / Support', 'General Questions / Support'), ('Technical Issues', 'Technical Issues'), ('Media / Press Inquiry', 'Media / Press Inquiry'), ('Other', 'Other')], max_length=100),
        ),
    ]
