# Generated by Django 4.1.13 on 2026-01-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_feedback_alter_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('about', models.TextField()),
                ('instagram_followers', models.PositiveIntegerField()),
                ('years_active', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField()),
                ('runway_shows', models.PositiveIntegerField()),
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
