# Generated by Django 4.1.13 on 2026-01-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_modelprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='multiple_images',
            field=models.JSONField(blank=True, default=list, help_text='Store multiple image paths', null=True),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='model_profiles/profile_images/'),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
