# Generated by Django 4.1.13 on 2026-01-31 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_modelprofile_multiple_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprofile',
            name='multiple_images',
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='ModelProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/multiple/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.modelprofile')),
            ],
        ),
    ]
