# Generated by Django 4.1.13 on 2026-01-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_modelprofile_multiple_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/'),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/'),
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/'),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='model_profiles/profile_images/'),
        ),
        migrations.DeleteModel(
            name='ModelProfileImage',
        ),
    ]
