# Generated by Django 4.1.13 on 2026-01-31 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_modelprofile_image_1_modelprofile_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='instagram_followers',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='registered_at',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='runway_shows',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='modelprofile',
            name='years_active',
        ),
        migrations.CreateModel(
            name='Modeldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('about', models.TextField()),
                ('instagram_followers', models.PositiveIntegerField()),
                ('years_active', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField()),
                ('runway_shows', models.PositiveIntegerField()),
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='model_profiles/profile_images/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='model_profiles/multiple_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='user.modelprofile')),
            ],
        ),
    ]
