# Generated by Django 4.1.13 on 2026-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_modelprofile_about_remove_modelprofile_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='model_profiles/profile_images/'),
        ),
    ]
