# Generated by Django 4.1.13 on 2026-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_modeldetails_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='instagram_followers',
            field=models.TextField(),
        ),
    ]
