# Generated by Django 4.1.13 on 2026-02-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_modeldetails_instagram_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='date_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='instagram_followers',
            field=models.CharField(max_length=50),
        ),
    ]
