# Generated by Django 4.1.13 on 2026-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_modeldetails_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
    ]
