# Generated by Django 4.1.13 on 2026-02-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_modeldetails_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='image_10',
        ),
    ]
