# Generated by Django 4.1.13 on 2026-02-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_modeldetails_image_10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='height_cm',
        ),
    ]
