# Generated by Django 4.1.13 on 2026-02-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_modeldetails_height_cm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.modelprofile')),
            ],
        ),
    ]
