# Generated by Django 4.1.13 on 2026-02-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='model_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
