# Generated by Django 4.2 on 2026-02-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_appointment_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Technical Issues', 'Technical Issues'), ('Apply to become a model', 'Apply to become a model'), ('Agency / Brand Collaboration Inquiry', 'Agency / Brand Collaboration Inquiry'), ('General Questions / Support', 'General Questions / Support'), ('Media / Press Inquiry', 'Media / Press Inquiry'), ('Other', 'Other')], max_length=100),
        ),
    ]
