# Generated by Django 4.2 on 2026-02-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
