# Generated by Django 4.2 on 2026-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetails',
            name='password',
            field=models.CharField(default='123456', max_length=100),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
