# Generated by Django 4.2 on 2026-03-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_modeldetails_password_modeldetails_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='username',
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
