# Generated by Django 4.2 on 2026-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_modeldetails_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
