# Generated by Django 4.2 on 2026-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_modeldetails_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetails',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
