# Generated by Django 4.2 on 2026-03-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_modeldetails_password_modeldetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='date_of_birth',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='password',
            field=models.CharField(default='pass', max_length=100),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
