# Generated by Django 4.2 on 2026-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_modeldetails_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldetails',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
