# Generated by Django 4.2 on 2026-03-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_modeldetails_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='username',
        ),
    ]
