# Generated by Django 4.2 on 2026-03-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_modeldetails_password_modeldetails_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='modeldetails',
            name='username',
        ),
    ]
