# Generated by Django 4.2 on 2026-03-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_modeldetails_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetails',
            name='password',
            field=models.CharField(default='123456', max_length=100),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
